### ISSUE TITLE
`serviceContext` not sent with `uncaughtException`

### ISSUE THREAD

**Issue by kilianc** [GoogleCloudPlatform/cloud-errors-nodejs#101]
Is it possible that this is due to https://github.com/GoogleCloudPlatform/cloud-errors-nodejs/blob/v0.1.x/lib/interfaces/uncaught.js#L56 calling `sendError` instead of `report` ?

**Comment by cristiancavalli** [comment]
Thanks for the report @kilianc !
Will take a look into this asap. `sendError` is the API actual client transport method so I do not think it's that but I will double-check to make sure.

**Comment by kilianc** [comment]
Just to give a little bit more context this is what it looks like in the console, same setup we get errors for all the `report` calls we do ourselves on `500s` but not on `uncaughtException`

![](https://www.dropbox.com/s/r88n7qua9jbryuj/Screenshot%202017-03-28%2011.33.35.png?dl=1)

**Comment by cristiancavalli** [comment]
@kilianc Thanks for pointing this out. We are working on having a better set of integration tests to avoid this in the future and these tests should hopefully be rolled out soon. In regards to this bug I think I have a viable fix posted for review here:
https://github.com/GoogleCloudPlatform/cloud-errors-nodejs/pull/102

Thanks again for pointing this out

**Comment by DominicKramer** [comment]
This issue has been closed since it is now being tracked in the [google-cloud-node/error-reporting](https://github.com/GoogleCloudPlatform/google-cloud-node/tree/master/packages/error-reporting) repository under issue [#2297](https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2297).
