### ISSUE TITLE
Use @google/cloud-diagnostics-common

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/cloud-errors-nodejs#15]
Some of the functionality (logger, auth, retry) should be refactored/reused from the @google/cloud-diagnostics-common module.

**Comment by cristiancavalli** [comment]
Somethings to think about in moving over/refactoring the shared client:
* Can't break existing interfaces unless we want to change code in all three libraries
* Implementing a request queue outside of passing around individual object will probably require a change to the interface
* How would we generalize and implement things like batching? Would this be handled by application calls? Then each application does its own batching on top on the transport library?

**Comment by matthewloring** [comment]
I don't believe we should move buffering under the umbrella of the diagnostics common. Data can be buffered inside the agents in whatever form makes the most sense and a single outgoing request can be made using diagnostics common. It is unfortunate that the current errors API does not support batch multiple errors into a single request but I am not sure that batching multiple requests provides additional value.
