### ISSUE TITLE
User should be warned when key has not been provided

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/cloud-errors-nodejs#2]
I just tried the agent in a sample app running locally where I didn't provide a key in the config or in through the environment. The error reporting agent cannot publish errors in this case (expected) but it doesn't provide any indication to the user that it has been unsuccessful at publishing and the user is left wondering whether the errors are actually going to show up on the Stackdriver console.

```
❯ node index.js
Example app listening!
SyntaxError: Unexpected token :
    at Object.parse (native)
    at /Users/ofrobots/src/node-hello/index.js:15:8
    at Layer.handle [as handle_request] (/Users/ofrobots/src/node-hello/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/ofrobots/src/node-hello/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/ofrobots/src/node-hello/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/ofrobots/src/node-hello/node_modules/express/lib/router/layer.js:95:5)
    at /Users/ofrobots/src/node-hello/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/Users/ofrobots/src/node-hello/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/ofrobots/src/node-hello/node_modules/express/lib/router/index.js:271:10)
    at expressInit (/Users/ofrobots/src/node-hello/node_modules/express/lib/middleware/init.js:33:5)
^C
```

I hit Ctrl-C after a minute. I think it would be useful if we could tell user about the lack of authentication information. The sooner the better, i.e. it would be best if we didn't have to wait till the first error before we told the user that their errors won't be reported to the API.

**Comment by cristiancavalli** [comment]
This is partially provided by Add e2e tests #14
(https://github.com/GoogleCloudPlatform/cloud-errors-nodejs/pull/14/files#diff-e0f8b689bf9d97a6c0922d016b797110R175)

This will be further supplemented by another patch after e2e tests are accepted

**Comment by cristiancavalli** [comment]
@ofrobots Should this only include an environmental variable check against GOOGLE_APPLICATION_CREDENTIALS? Since the authentication is handled by google-auth-library I'm not entirely sure of what we should check.

**Comment by ofrobots** [comment]
I agree that it seems awkward to check for an env. variable. Ideally we should be able to send something to the API and verify that the credentials are correct. Is there a way for you to send an error (or perhaps a malformed error packet) to the API and see if it gets rejected due to lack  of credentials.

**Comment by cristiancavalli** [comment]
@ofrobots We could send a malformed request but this seems really hacky way to try and solve this. Maybe we should petition for an endpoint where auth could be tested and that is the purpose of the endpoint. Otherwise it seems like we would just be wasting cycles doing a broken request for 90% of the cases that users will see

**Comment by ofrobots** [comment]
Thinking more about this, I don't think we need to send anything to the API to figure out that the user has not provided credentials. Here are the mechanisms we document in our [README](https://github.com/GoogleCloudPlatform/cloud-errors-nodejs#setup):

* GCLOUD_APPLICATION_CREDENTIALS
* config.key
* config.keyFile

If none of these have been provided (we can determine this at startup) we should log an error. This will handle the majority of the cases wherein the user simply forgot to provide credentials. It is still possible that they could provide invalid credentials, but that is a separate issue.

@cristiancavalli assigning back to you.

**Comment by ofrobots** [comment]
It seems that the README is missing some mechanisms for auth that we also support:

* gcloud default auth credentials
* key.credentials
