### ISSUE TITLE
README should lead with GCP instructions first, running on other platforms next

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/cloud-errors-nodejs#24]
Currently we lead users down a path that would work for other cloud providers as well as GCP.  I'd prefer to keep the quickstart light and quick assuming they're using our platform.  Looking for discussion!

**Comment by steren** [comment]
I agree. I'll change the quickstart to "Quickstart on Google Cloud Platform", with instructions that should work when authentication is there.

**Comment by steren** [comment]
Note that I updated the README, but still could not make it work on Flex, as tracked in https://github.com/GoogleCloudPlatform/cloud-errors-nodejs/issues/28
