### ISSUE TITLE
I should not need to provide projectId on GAE Flex (use GAE_LONG_APP_ID?)

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/cloud-errors-nodejs#29]
On GAE Flex, the GLCOUD_PROJECT environment variable is not available.

I do not expect to need to explicitly provide projectId in my code or setting an environment variable at startup. My GAE instances should be aware of the project then run in.
  
The projectId can be retrieve from the `GAE_LONG_APP_ID`.
As documented [here](https://cloud.google.com/appengine/docs/flexible/nodejs/runtime):

> GAE_LONG_APP_ID is set to the Project ID associated with your application

**Comment by ofrobots** [comment]
I think we should use the Metadata service to query out the project id like we do on the other agents. @steren: would this work for you?

**Comment by steren** [comment]
Sounds good to me, especially if this is what is done in other agents.

**Comment by steren** [comment]
I confirm that by using the code at HEAD, I did not need to provide an explicit 'projectId' to see errors reported in Error Reporting.
