### ISSUE TITLE
Warning should be logged if error cannot be reported

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/cloud-errors-nodejs#40]
If an error cannot be reported (the API returns something else than 200), a warning should be logged saying that the error could not be reported.

As far as I know, it is not the case today: I have an app that reports errors, errors are not appearing in the UI despite the message payload being a valid stacktrace.

I would guess the API returns something else than 200 if called.

**Comment by ofrobots** [comment]
@cristiancavalli: Any status update on this?

**Comment by cristiancavalli** [comment]
@ofrobots resolved via #43
