### ISSUE TITLE
report(string) does not report errors

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/cloud-errors-nodejs#41]
calling report with a simple string does not report errors in Error Reporting.
Example code I used on GAE Flex:
```JS
app.get('/', function (req, res) {
  errorHandler.report('simple text test steren');
  res.status(200).send('ok');
});
```

The reason might be because of what is sent to the API:
If you are not sending a stacktrace in the message attribute, then you must provide context.reportLocation otherwise the backends are not able to group the errors and will ignore it.
See https://cloud.google.com/error-reporting/docs/formatting-error-messages

for the client-side JavaScript library, I actually always create an Error from the message string: see https://github.com/GoogleCloudPlatform/stackdriver-errors-js/blob/master/stackdriver-errors.js#L87

**Comment by cristiancavalli** [comment]
@steren I've just scaffolded out a change which introduces report location information into a string-as-input case, but I still can't get something to show up on the interface. This is roughly what I am sending over the wire:

```JSON
{
	"eventTime": "2016-07-29T22:52:15.727Z",
	"serviceContext": {
		"service": "",
		"version": ""
	},
	"message": "Sample string",
	"context": {
		"httpRequest": {
			"method": "",
			"url": "",
			"userAgent": "",
			"referrer": "",
			"responseStatusCode": 0,
			"remoteIp": ""
		},
		"user": "cristiancavall",
		"reportLocation": {
			"filePath": "/Users/cristiancavall/googlesrc/cloud-errors-nodejs/lib/error-handlers/string.js",
			"lineNumber": 36,
			"functionName": "handleStringAsError"
		}
	}
}
```

Anything I'm missing? I can swap this structure's `message` property with a regular JS stack trace and it shows up in the UI

**Comment by steren** [comment]
For the moment, the message needs to be a minimum of 3 tokens to be grouped
by the Error Reporting backends.

Try with "message": "Sample test string",

**Comment by cristiancavalli** [comment]
Hey Steren, just tried the following and it is still not showing up in the ui:

```JSON
{
	"eventTime": "2016-07-31T01:25:13.673Z",
	"serviceContext": {
		"service": "",
		"version": ""
	},
	"message": "Sample test string",
	"context": {
		"httpRequest": {
			"method": "",
			"url": "",
			"userAgent": "",
			"referrer": "",
			"responseStatusCode": 0,
			"remoteIp": ""
		},
		"user": "cristiancavall",
		"reportLocation": {
			"filePath": "/Users/cristiancavall/googlesrc/cloud-errors-nodejs/tests/test-servers/manual_scaffold_server.js",
			"lineNumber": 17,
			"functionName": "test"
		}
	}
}
```

If I swap the message field contents with a string stack trace it shows up

**Comment by steren** [comment]
Sorry, it seems that there is an issue in the backend that was ignoring messages without stack traces. The fix should be deployed to prod this week.

But also, `serviceContext` is required, so you should try to test with a non empty `serviceContext.service`. But isn't the library supposed to send a default value for it?

**Comment by cristiancavalli** [comment]
@steren pinging on the status of this. Just tried this and did not see anything happen with the above payload.

**Comment by steren** [comment]
Hi cristiancavalli@,
The backend issue is now fixed. I could successfully report an error without stacktrace, providing that I give serviceContext and reportLocation

**Comment by cristiancavalli** [comment]
@steren 
Given that these fields are manually set by providing them in an object:

```JS
.report({message: 'a test string', reportLocation: {...}, serviceContext: {...}})
```

then the error will be correctly logged. Since default values were not established for these fields as requirements and I can't find what would be the default values then these fields will have to be provided explicitly until a set of defaults is agreed upon.

**Comment by steren** [comment]
`report('string', callback)` is defined as one flavor of the require() method in in our requirment document.

Indeed:

* `serviceContext` is either populated automatically or set by the user at initialization,
* `reportLocation` is expected to be set automatically by the library.

As an example, the simple [client side JS library](https://github.com/GoogleCloudPlatform/stackdriver-errors-js#usage) is supporting this signature.

**Comment by cristiancavalli** [comment]
From the sample you provided 'web' looks like a viable default serviceContext. Report location is a bit trickier - since without a stack trace we would have to fabricate one from generating an error since that information is not readily available from just  a string being logged. I'll look into it.

**Comment by steren** [comment]
Thanks. I think you are already using `"nodejs"` as the default `serviceContext.service` value, correct? This is not specific to `report(string)`, it should also apply to `report(Error)`.
Yes, generating an error and picking the first frame is what I do on the client.

**Comment by cristiancavalli** [comment]
Hey @steren thanks again for the guidance - will update with the default to the current pull, take a look @ #63. Just tested it with my setup and it looks to be functioning. The sample test file updated in it is attempting to model the desired signature.
