### ISSUE TITLE
Use the google-cloud-node API wrappers if it makes sense.

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/cloud-errors-nodejs#59]
https://github.com/googleapis/api-client-staging/tree/master/generated/nodejs/google-cloud-node/packages/errorreporting
are generated API wrappers on top of the Error Reporting API. Using them from this idomatic instrumentation module would make sense.

**Comment by cristiancavalli** [comment]
@steren It looks like this uses GRPC. The addition of this as a dependency would substantially increase its size and we already are having issues with dependency size. Furthermore this would add a native module as a dependency -- which would vastly increase install times. 
Are we okay with accepting these costs to use the GRPC interface?

cc @ofrobots

**Comment by DominicKramer** [comment]
This issue has been closed since it is now being tracked in the [google-cloud-node/error-reporting](https://github.com/GoogleCloudPlatform/google-cloud-node/tree/master/packages/error-reporting) repository under issue [#2300](https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2300).
