### ISSUE TITLE
Add description and website to the GitHub repo

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/cloud-errors-nodejs#6]
Currently it reads "No description or website provided."
It should say: "Node.js module for Google Stackdriver Error Reporting"

Also use https://cloud.google.com/error-reporting/ as website

**Comment by cristiancavalli** [comment]
@steren I think this was solved by #13

Throughout the readme I use `https://cloud.google.com/error-reporting/` for links, is there anywhere else I should like with this url or can I close this issue out?

**Comment by ofrobots** [comment]
This was about the GitHub repo itself. Fixed.
