### ISSUE TITLE
The module should work with no config on Google Cloud Functions environment

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/cloud-errors-nodejs#62]
Using the module on Google Cloud Functions should not require to provide a serviceContext, projectID or authentication.

The Function name should be mapped to serviceContext.service.

Note that Cloud Functions already logs exceptions and Error Reporting picks them up. But users might want to explicitly use this Node.js module for having more control and passing more metadata.

**Comment by DominicKramer** [comment]
This issue has been addressed in [PR #70](https://github.com/GoogleCloudPlatform/cloud-errors-nodejs/pull/70).
