### ISSUE TITLE
Errors doesn't work with Node v0.12 unless --harmony flag is enabled

### ISSUE THREAD

**Issue by kjin** [GoogleCloudPlatform/cloud-errors-nodejs#65]
Koa officially doesn't support v0.12 unless --harmony flag is enabled

https://github.com/koajs/koa#installation

Specifically, yield doesn't work (and as far as I know, is the preferred way to write Koa middleware).

Possible changes:
* Update README to state that --harmony is necessary for v0.12
* Change error-handling middleware in this library to not use yield
* Change error-handling middleware to load lazily (not sure if this is feasible)
* Don't do anything Koa-related in v0.12 without --harmony
* Drop support for v0.12 altogether

**Comment by ofrobots** [comment]
@cristiancavalli: thoughts? We shouldn't require `--harmony` unless the user is using koa (in which case there is no problem as they are using `--harmony` already. Is there a way to avoid the yield unless the koa hooks actually get used?

**Comment by kjin** [comment]
@cristiancavalli soft bump.

One workaround I can do for the open pull request is to check process.version (and process.args) and only add `koa` as a member of the agent if they suggest that the current environment allows it.

**Comment by ofrobots** [comment]
@kjin: SGTM, but instead of a version check, could you feature detect? http://stackoverflow.com/questions/23096064/how-can-i-feature-detect-es6-generators

**Comment by cristiancavalli** [comment]
That sounds good to me as well

**Comment by DominicKramer** [comment]
This issue has been addressed in [PR #68](https://github.com/GoogleCloudPlatform/cloud-errors-nodejs/pull/68).
