### ISSUE TITLE
Significant amount of dependencies

### ISSUE THREAD

**Issue by 1602** [GoogleCloudPlatform/cloud-errors-nodejs#76]
```sh
$  yarn add @google/cloud-errors
$  du -hs node_modules/
 18M    node_modules/
$  ls -la node_modules/ | wc -l
 100
```

This is meant as a utility project to be used in microservices. It should not add 18MB of data to microservice. Would it be possible to reduce amount of dependent code this project is adding?

**Comment by ofrobots** [comment]
Thanks for the bug report & feedback. We'll take a look at what we can trim.

From an initial scan, the biggest dependencies are (sizes in KiB):

```
1380	google-auth-library
2568	node-forge
2884	moment
4960	lodash
```

`lodash` is depended upon (transitively) from `request`, so that is unavoidable. We could trim `moment` from `@google/cloud-diagnostics-common`. I will take a look in more detail soon.

**Comment by ofrobots** [comment]
Dropped dependency on `moment` in https://github.com/GoogleCloudPlatform/cloud-diagnostics-common-nodejs/pull/31. We will pick this change up in the next release.

Most of everything else is transitively needed from `request` which is needed locally and by `google-auth-library`. I don't see an easy way to avoid using `request` in the foreseeable future in `google-auth-library`. Typical web apps are likely to depend upon `request` one way or the other, and removing it isn't necessarily going to be a win.

@1602: Do you see something obvious that can be removed that I don't see? Do any of the dependencies of your app overlapping with the dependencies of this module? i.e. how much incremental footprint does it add once you add it to your service.

**Comment by 1602** [comment]
@ofrobots thanks for prompt reply. I'd recommend limiting lodash usage only to what needed, i.e. require('lodash.pick'), it is huge and mostly not used.

**Comment by ofrobots** [comment]
@1602 We already have a PR that does this: https://github.com/GoogleCloudPlatform/cloud-errors-nodejs/pull/78. However, this will actually increase disk footprint as full lodash is being used by one of our indirect dependencies `@google/cloud-errors → @google/cloud-diagnostics-common → google-auth-library → request → form-data → async → lodash`. Us switching to individual lodash functions would actually more code in `node_modules`.

**Comment by 1602** [comment]
Thanks @ofrobots, fair enough. Also, after closer look i see that this issue is not related to this project, as big stuff coming from other packages. So, perhaps worth closing this issue.

**Comment by ofrobots** [comment]
Sounds good. Thanks for bringing this to our attention.
