### ISSUE TITLE
Using start in version 0.1.0 works only in production

### ISSUE THREAD

**Issue by wenderjean** [GoogleCloudPlatform/cloud-errors-nodejs#93]
I have a problem using version `0.1.0`, `ignoreEnvironmentCheck` attribute is ignored and only works in production.

With `master` source using constructor initialization It doesn't happen. 

```
const errors = require('@google/cloud-errors').start({
    ignoreEnvironmentCheck: true,
    logLevel: 1
});

errors.report(...);
```

**Comment by ofrobots** [comment]
Thanks for reporting the issue @wenderjean. I just published a patch-level update `v0.1.1` that fixes some issues, especially with indicating what went wrong if the agent wasn't able to publish traces. Can you give that a try?

> With master source using constructor initialization It doesn't happen

Can you elaborate about what you see with `master`? Does `ignoreEnvironmentCheck` continue to be ignored, or do things work correctly?

**Comment by wenderjean** [comment]
@ofrobots In `master` branch `ignoreEnvironmentCheck` is considered and It works well.
I'll try `v0.1.1` and let you know any problem.
Thank you

**Comment by wenderjean** [comment]
@ofrobots Works fine, thank you again.
